apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
   type: pubsub.rabbitmq
   version: v1
   metadata:
   - name: host
     value: "amqp://guest:guest@localhost:5672"
   - name: deletedWhenUnused
     value: "false"
   - name: durable
     value: "true"
   - name: deliveryMode
     value: "2"
   - name: prefetchCount
     value: "5"
   - name: requeueInFailure
     value: "false"
   - name: backOffMaxRetries
     value: "3"
   - name: enableDeadLetter
     value: "true"
